# .github/workflows/example.yml

name: sync_upstream
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '*/60 * * * *'
  workflow_dispatch: # on button click
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.VUL_DRILLER_TOKEN}}
      - name: config
        run: |
          git config --global user.name 'ahouseholder'
          git config --global user.email 'ahouseholder@users.noreply.github.com'
      - name: pull
        run: |
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
      - name: fetch upstream
        run: |
          git remote add upstream https://github.com/offensive-security/exploitdb.git
          git fetch upstream
      - name: delete date tags
        run: git tag -d $(git tag -l "20*")
      - name: merge and push
        run: |
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
